### ISSUE TITLE
netherite tools/items not working

### ISSUE THREAD

**Issue by Sylensky** [Crazy-Crew/CrazyEnchantments#670]
**Describe the bug**
Enchantments in book form dont apply on netherite tools/armor and just sent the chat message the item loved this book. However the enchantment never gets applied to it.

**Versions (please complete the following information):**
 - Minecraft Server Version: git-Paper-132 (MC: 1.19.2)
 - Plugin Version: 1.9.5-42

**Pastebin any errors in console**
there are no errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/57076968/187266780-9b170da4-cc4f-4f39-a944-522b8b60b64c.png)

**Comment by RyderBelserion** [comment]
It does not work in Creative Mode.

**Comment by Sylensky** [comment]
oh yes i can confirm that. wierd enough it did work with creative before.
