### ISSUE TITLE
StickyShot Enchantment destroying blocks

### ISSUE THREAD

**Issue by LemonCat129** [Crazy-Crew/CrazyEnchantments#684]
When shooting a mob next to a wall, the 3x3 of cobwebs that spawn will destroy blocks in the wall so they can be placed

**Comment by LemonCat129** [comment]
1.9.5 Snapshot

**Comment by RyderBelserion** [comment]
You are on a outdated build.

https://ci.crazycrew.us/job/CrazyEnchantments/13/artifact/jars/CrazyEnchantments-1.9.7-b13-SNAPSHOT.jar
