### ISSUE TITLE
when i try to enchant my armor this happend: you have hit the max amount of enchantments an item can have. Pls help me ;-;

### ISSUE THREAD

**Issue by ImNotQuan** [Crazy-Crew/CrazyEnchantments#691]
i read some issue they saying about add crazyenchantments.limit but idk where and how to do it

**Comment by RyderBelserion** [comment]
https://github.com/Crazy-Crew/CrazyEnchantments/wiki/Commands-and-Permissions#options

Use a permissions plugin like LuckPerms to add these permissions.

**Comment by ImNotQuan** [comment]
it works thx
btw is the limits is limited or limitless

**Comment by ImNotQuan** [comment]
> https://github.com/Crazy-Crew/CrazyEnchantments/wiki/Commands-and-Permissions#options
> 
> Use a permissions plugin like LuckPerms to add these permissions.
