### ISSUE TITLE
[Bug Report]:  Blast and some enchantments not working v1.9.8.2

### ISSUE THREAD

**Issue by TBAProgramming** [Crazy-Crew/CrazyEnchantments#705]
### Video

[https://imgur.com/oidgYyX](url)
### Server Version

1.19.4

### Server Platform

Paper

### Describe the bug

**i have bug with some enchantments like blast not working in crazy enchantments verison v1.9.8.2 lastest
i trired ervery way but not working
any staff can fix it?
and server verison: paper v1.19.4**

see that video to trust: [https://imgur.com/oidgYyX](url)

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by RyderBelserion** [comment]
Did you read the change log before using the plugin?

**Comment by TBAProgramming** [comment]
wait

**Comment by TBAProgramming** [comment]
i not found anyerror/bug in log/console
see video [https://imgur.com/oidgYyX](url)

**Comment by RyderBelserion** [comment]
So did you read the change log on Modrinth?

**Comment by TBAProgramming** [comment]
yeah

**Comment by RyderBelserion** [comment]
If you did, you'd find the solution.

**Comment by TBAProgramming** [comment]
i did it

**Comment by TBAProgramming** [comment]
i did /lp user sbvwslyz permission set crazyenchantments.blast true

**Comment by RyderBelserion** [comment]
If you added the permission `crazyenchantments.blast.use` then it will work.

**Comment by TBAProgramming** [comment]
that still not working

**Comment by RyderBelserion** [comment]
crazyenchantments.blast.use

**Comment by TBAProgramming** [comment]
i did it

**Comment by TBAProgramming** [comment]
oh

**Comment by TBAProgramming** [comment]
ok i will do it

**Comment by TBAProgramming** [comment]
oh ty worked!

**Comment by TBAProgramming** [comment]
> crazyenchantments.blast.use

tysm

**Comment by RyderBelserion** [comment]
Yay!

**Comment by TBAProgramming** [comment]
but why blast not working in netherite/beacons?

**Comment by RyderBelserion** [comment]
You have to add the blocks to the BlockList.yml

**Comment by TBAProgramming** [comment]
i not found blocklist.yml in folder plugin

**Comment by RyderBelserion** [comment]
It's there.

**Comment by TBAProgramming** [comment]
ohhh wait i need to reload /ce reload

**Comment by TBAProgramming** [comment]
works ty!

**Comment by TBAProgramming** [comment]
can i remove permission and make blast work for all without permission or not?

**Comment by neverabsolute** [comment]
![image](https://user-images.githubusercontent.com/58273860/232261851-f913665b-6d4f-47d4-96ca-bba9bef9207b.png)

**Comment by RyderBelserion** [comment]
> can i remove permission and make blast work for all without permission or not?

No, It's hard-coded for the time being.

**Comment by TBAProgramming** [comment]
> > can i remove permission and make blast work for all without permission or not?
> 
> No, It's hard-coded for the time being.

ok
