### ISSUE TITLE
[Api Update]: Console spam

### ISSUE THREAD

**Issue by Skippy8787** [Crazy-Crew/CrazyEnchantments#710]
### Server Version

1.19.4

### Server Platform

Paper

### Describe the bug

Consistant spamming of the console with the following 
![image](https://github.com/Crazy-Crew/CrazyEnchantments/assets/108057642/e2f24e08-8db4-4298-8490-e52893becb86)

### Steps to reproduce

Start server
Wait three seconds 
spam.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by RyderBelserion** [comment]
I assume you are using FactionsUUID

Try updating to later versions @ https://www.spigotmc.org/resources/factionsuuid.1035

**Comment by Skippy8787** [comment]
I'm using saberfactions. Not factionsuuid.
Thanks for the quick response.
