### ISSUE TITLE
[Bug Report]: The commands and their menu do not work

### ISSUE THREAD

**Issue by Neferet-0** [Crazy-Crew/CrazyEnchantments#715]
### Server Version

1.19.4

### Server Platform

Spigot

### Describe the bug

Server Version : 1.19.2
Server Platform (Aternos) Mohist

in-game commands like:
**/gkit** opens the menu, and when selecting the kit, it only moves the pane.

When trying to give a kit: with the following command:
**/gkit Hero**
We get this message: "**An internal error occurred while waiting to perform this command**"

All menus move objects and do not validate.
Server Logs : <https://mclo.gs/sveYe47>

Screenshot : 
https://prnt.sc/HxzftJYrPZTx
https://prnt.sc/eJgoF-lCGtaL
https://prnt.sc/nc9zTmMtqM_0

### Steps to reproduce

i don't know

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
We dont support Mohist, Reproduce on a normal paper server.

**Comment by Neferet-0** [comment]
Thanks for the information! 
But it's weird that arternos offers it in this version :/
