### ISSUE TITLE
[Bug Report]: veinminer has a BUG in mining

### ISSUE THREAD

**Issue by Maorct** [Crazy-Crew/CrazyEnchantments#736]
### Server Version

1.20.2

### Server Platform

Paper

### Describe the bug

When mining, it will only be chained, but it will not destroy the targeted mineral.

When only one mineral will not be able to excavate break.

The test was based on paper 1.20.2 using only the Crazy Enchantments plugin and nothing else.

[https://s2.loli.net/2023/11/05/LJoA8F3EBGk6HfZ.png](url)

[https://s2.loli.net/2023/11/05/1RyxT5kJbBzXG7l.png](url)

### Steps to reproduce

1.Use the latest version of paper 1.20.2 and Crazy Enchantments v2.1.2.
2.Enter the game to place the ore.
3.Add veinminer enchantment to pickaxe.
4.The BUG can be reproduced by mining the ore.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
Join the discord and grab one of the recent builds in #crazy-enchantments. It probably is already fixed

**Comment by Maorct** [comment]
The latest version fixes this problem, thanks.
Have a nice day.
