### ISSUE TITLE
[Bug Report]: Server error, could not load

### ISSUE THREAD

**Issue by Mieszko581945** [Crazy-Crew/CrazyEnchantments#747]
### Server Version

1.20.2

### Server Platform

Spigot

### Describe the bug

I have spigot 1.20.2 Aternos server with 3 working plugins: ThrowableFireballs, SafeTrade and SkinRestorer. I tried yesterday add new plugin: CrazyEnchantments. But on every version, even the newest, it crashes and doesn't load. Where is reason? Please, can someone help, but not by only closing thread and ticking "completed"...? Please so much.

Here is log from server: https://mclo.gs/AaiRaSR

### Steps to reproduce

Just install CrazyEnchantments on Aternos for example on 1.20.2 or 1.19.4 and wait for first  readings of error from this plugin

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
You need to use https://papermc.io to use CrazyEnchantments.

**Comment by Mieszko581945** [comment]
Really? Okay. Thanks so much. But... only one more question: does it means, that this plugin is incompatibile with spigot at all?

**Comment by ryderbelserion** [comment]
which is why we aren't likely uploading CrazyEnchantments anymore on Modrinth.

**Comment by Mieszko581945** [comment]
aaa, okay. And all clear. Thanks for help!
