### ISSUE TITLE
[Feature Request]: Adjustment of Enchantments

### ISSUE THREAD

**Issue by RulerOfEternity** [Crazy-Crew/CrazyEnchantments#757]
### Describe the feature

1. Voodoo and Fortify (Both enchantments have the exact same effects and levelling, and both apply to the exact same equipment), I suggest one should give another effect, it doesn't matter what, as long as it's a negative effect not given by any other armor enchantment.

**Comment by ryderbelserion** [comment]
![image](https://github.com/Crazy-Crew/CrazyEnchantments/assets/52214219/90fa5caa-40a6-4e84-a17b-c9f801bf4215)

One heals yourself, The other steals

**Comment by RulerOfEternity** [comment]
Edited!

**Comment by RulerOfEternity** [comment]
For the first three rows, the changes could be as simple as just modifying the maximum level natively supported, but honestly it would be much better if they gave out different effects altogether to make the enchants more unique.

**Comment by RulerOfEternity** [comment]
Perhaps Fortify can have a chance of giving the attacker Instant Damage (the potion effect) or nausea.
