### ISSUE TITLE
Add 1.21 support

### ISSUE THREAD

**Issue by tomasalias** [Crazy-Crew/CrazyEnchantments#835]
### Plugin Version

latest

### Server Version

1.21

### Server Platform

Paper

### Describe the bug

Doesn't work

### Steps to reproduce

Start the server

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
We dont support 1.21 yet, I will not release 1.21 builds until Paper announces all patches and rewrites they plan are added.

**Comment by tomasalias** [comment]
> We dont support 1.21 yet, I will not release 1.21 builds until Paper announces all patches are added and rewrites of key systems like chunks they are actively working on are done. They are still only offering experimental downloads.

Lazy
