### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by slick432** [Crazy-Crew/CrazyEnchantments#850]
### Spark link

https://ci.lucko.me/job/spark/443/artifact/spark-bukkit/build/libs/spark-1.10.97-bukkit.jar

### Plugin Version

1.21.1

### Server Version

1.20.1

### Server Platform

Paper

### Describe the bug

So basically i dont really know if its a bug or not but when i was gonna enchant my helmet with a custom enchantment it said u cant add any more enchantments but i didnt have one single enchantment on it?

### Steps to reproduce

Didnt work.

### Additional context

no.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
![image](https://github.com/user-attachments/assets/ddb47e1d-3a04-4dc6-b329-1b4d909f4d30)
