### ISSUE TITLE
sticky navbar 

### ISSUE THREAD

**Issue by Shrutibansal22** [Crazy-Crew/CrazyEnchantments#860]
### Describe the feature

@Crazy-Crew
i wanted to add changes to navbar and footer.
kindly assign me this issue under hacktober-fest

**Comment by ryderbelserion** [comment]
CrazyEnchantments isn't a website.

**Comment by ryderbelserion** [comment]
CrazyEnchantments isn't a website. It's a plugin written in Java for Minecraft.

**Comment by Shrutibansal22** [comment]
> CrazyEnchantments isn't a website. It's a plugin written in Java for Minecraft.

ok sir
