### ISSUE TITLE
GKit Gems

### ISSUE THREAD

**Issue by basileus956** [Crazy-Crew/CrazyEnchantments#866]
### Describe the feature

The GKit gem is basically an easier way to grant GKits to people, with the GKit being stored inside an item (like a diamond) and 
when that item is right-clicked it's gone and replaced with the GKit it's supposed to contain.

/ce kitgem [GKit] (player) - player field being optional and if not filled is granted to the person executing the command.
It can especially help with servers selling GKits and not having to worry about enough sufficient inventory space.

My request is inspired by CosmicPvP but the difference is that in Cosmic the GKit gems grant access forever whereas in this request I want the gems to give the kit once, not the permission to access it forever.

### Other

![image](https://github.com/user-attachments/assets/df252cf8-fb74-40a7-800c-1085a57f4ae3)

**Comment by ryderbelserion** [comment]
We have a plugin for that, CrazyVouchers which can do what you want.
